// flow-typed signature: 5398da9c23c361d1ef040b9a18847f84
// flow-typed version: <<STUB>>/numbro_v1.6.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'numbro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'numbro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'numbro/dist/languages' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/cs-CZ.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/da-DK.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/de-CH.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/de-DE.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/en-GB.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/en-ZA.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/es-AR.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/es-ES.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/et-EE.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/fa-IR.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/fi-FI.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/fil-PH.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/fr-CA.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/fr-CH.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/fr-FR.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/he-IL.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/hu-HU.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/it-IT.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/ja-JP.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/lv-LV.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/nb-NO.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/nl-BE.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/nl-NL.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/pl-PL.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/pt-BR.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/pt-PT.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/ru-RU.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/ru-UA.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/sk-SK.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/sv-SE.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/th-TH.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/tr-TR.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/uk-UA.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/languages/zh-CN.min' {
  declare module.exports: any;
}

declare module 'numbro/dist/numbro' {
  declare module.exports: any;
}

declare module 'numbro/dist/numbro.min' {
  declare module.exports: any;
}

declare module 'numbro/Gruntfile' {
  declare module.exports: any;
}

declare module 'numbro/languages/cs-CZ' {
  declare module.exports: any;
}

declare module 'numbro/languages/da-DK' {
  declare module.exports: any;
}

declare module 'numbro/languages/de-CH' {
  declare module.exports: any;
}

declare module 'numbro/languages/de-DE' {
  declare module.exports: any;
}

declare module 'numbro/languages/en-GB' {
  declare module.exports: any;
}

declare module 'numbro/languages/en-ZA' {
  declare module.exports: any;
}

declare module 'numbro/languages/es-AR' {
  declare module.exports: any;
}

declare module 'numbro/languages/es-ES' {
  declare module.exports: any;
}

declare module 'numbro/languages/et-EE' {
  declare module.exports: any;
}

declare module 'numbro/languages/fa-IR' {
  declare module.exports: any;
}

declare module 'numbro/languages/fi-FI' {
  declare module.exports: any;
}

declare module 'numbro/languages/fil-PH' {
  declare module.exports: any;
}

declare module 'numbro/languages/fr-CA' {
  declare module.exports: any;
}

declare module 'numbro/languages/fr-CH' {
  declare module.exports: any;
}

declare module 'numbro/languages/fr-FR' {
  declare module.exports: any;
}

declare module 'numbro/languages/he-IL' {
  declare module.exports: any;
}

declare module 'numbro/languages/hu-HU' {
  declare module.exports: any;
}

declare module 'numbro/languages/it-IT' {
  declare module.exports: any;
}

declare module 'numbro/languages/ja-JP' {
  declare module.exports: any;
}

declare module 'numbro/languages/lv-LV' {
  declare module.exports: any;
}

declare module 'numbro/languages/nb-NO' {
  declare module.exports: any;
}

declare module 'numbro/languages/nl-BE' {
  declare module.exports: any;
}

declare module 'numbro/languages/nl-NL' {
  declare module.exports: any;
}

declare module 'numbro/languages/pl-PL' {
  declare module.exports: any;
}

declare module 'numbro/languages/pt-BR' {
  declare module.exports: any;
}

declare module 'numbro/languages/pt-PT' {
  declare module.exports: any;
}

declare module 'numbro/languages/ru-RU' {
  declare module.exports: any;
}

declare module 'numbro/languages/ru-UA' {
  declare module.exports: any;
}

declare module 'numbro/languages/sk-SK' {
  declare module.exports: any;
}

declare module 'numbro/languages/sv-SE' {
  declare module.exports: any;
}

declare module 'numbro/languages/th-TH' {
  declare module.exports: any;
}

declare module 'numbro/languages/tr-TR' {
  declare module.exports: any;
}

declare module 'numbro/languages/uk-UA' {
  declare module.exports: any;
}

declare module 'numbro/languages/zh-CN' {
  declare module.exports: any;
}

declare module 'numbro/numbro' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/all' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/cs-CZ' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/da-DK' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/de-CH' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/de-DE' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/en-GB' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/en-US' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/en-ZA' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/es-AR' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/es-ES' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/et-EE' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/fa-IR' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/fi-FI' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/fil-PH' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/fr-CA' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/fr-CH' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/fr-FR' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/he-IL' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/hu-HU' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/it-IT' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/ja-JP' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/locale-codes' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/lv-LV' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/nl-BE' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/nl-NL' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/pl-PL' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/pt-BR' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/pt-PT' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/ru-RU' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/ru-UA' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/sk-SK' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/sv-SE' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/th-TH' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/tr-TR' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/uk-UA' {
  declare module.exports: any;
}

declare module 'numbro/tests/languages/zh-CN' {
  declare module.exports: any;
}

declare module 'numbro/tests/numbro/format' {
  declare module.exports: any;
}

declare module 'numbro/tests/numbro/manipulate' {
  declare module.exports: any;
}

declare module 'numbro/tests/numbro/misc' {
  declare module.exports: any;
}

declare module 'numbro/tests/numbro/unformat' {
  declare module.exports: any;
}

declare module 'numbro/tests/numbro/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'numbro/dist/languages.js' {
  declare module.exports: $Exports<'numbro/dist/languages'>;
}
declare module 'numbro/dist/languages.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages.min'>;
}
declare module 'numbro/dist/languages/cs-CZ.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/cs-CZ.min'>;
}
declare module 'numbro/dist/languages/da-DK.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/da-DK.min'>;
}
declare module 'numbro/dist/languages/de-CH.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/de-CH.min'>;
}
declare module 'numbro/dist/languages/de-DE.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/de-DE.min'>;
}
declare module 'numbro/dist/languages/en-GB.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/en-GB.min'>;
}
declare module 'numbro/dist/languages/en-ZA.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/en-ZA.min'>;
}
declare module 'numbro/dist/languages/es-AR.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/es-AR.min'>;
}
declare module 'numbro/dist/languages/es-ES.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/es-ES.min'>;
}
declare module 'numbro/dist/languages/et-EE.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/et-EE.min'>;
}
declare module 'numbro/dist/languages/fa-IR.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/fa-IR.min'>;
}
declare module 'numbro/dist/languages/fi-FI.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/fi-FI.min'>;
}
declare module 'numbro/dist/languages/fil-PH.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/fil-PH.min'>;
}
declare module 'numbro/dist/languages/fr-CA.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/fr-CA.min'>;
}
declare module 'numbro/dist/languages/fr-CH.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/fr-CH.min'>;
}
declare module 'numbro/dist/languages/fr-FR.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/fr-FR.min'>;
}
declare module 'numbro/dist/languages/he-IL.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/he-IL.min'>;
}
declare module 'numbro/dist/languages/hu-HU.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/hu-HU.min'>;
}
declare module 'numbro/dist/languages/it-IT.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/it-IT.min'>;
}
declare module 'numbro/dist/languages/ja-JP.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/ja-JP.min'>;
}
declare module 'numbro/dist/languages/lv-LV.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/lv-LV.min'>;
}
declare module 'numbro/dist/languages/nb-NO.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/nb-NO.min'>;
}
declare module 'numbro/dist/languages/nl-BE.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/nl-BE.min'>;
}
declare module 'numbro/dist/languages/nl-NL.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/nl-NL.min'>;
}
declare module 'numbro/dist/languages/pl-PL.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/pl-PL.min'>;
}
declare module 'numbro/dist/languages/pt-BR.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/pt-BR.min'>;
}
declare module 'numbro/dist/languages/pt-PT.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/pt-PT.min'>;
}
declare module 'numbro/dist/languages/ru-RU.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/ru-RU.min'>;
}
declare module 'numbro/dist/languages/ru-UA.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/ru-UA.min'>;
}
declare module 'numbro/dist/languages/sk-SK.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/sk-SK.min'>;
}
declare module 'numbro/dist/languages/sv-SE.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/sv-SE.min'>;
}
declare module 'numbro/dist/languages/th-TH.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/th-TH.min'>;
}
declare module 'numbro/dist/languages/tr-TR.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/tr-TR.min'>;
}
declare module 'numbro/dist/languages/uk-UA.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/uk-UA.min'>;
}
declare module 'numbro/dist/languages/zh-CN.min.js' {
  declare module.exports: $Exports<'numbro/dist/languages/zh-CN.min'>;
}
declare module 'numbro/dist/numbro.js' {
  declare module.exports: $Exports<'numbro/dist/numbro'>;
}
declare module 'numbro/dist/numbro.min.js' {
  declare module.exports: $Exports<'numbro/dist/numbro.min'>;
}
declare module 'numbro/Gruntfile.js' {
  declare module.exports: $Exports<'numbro/Gruntfile'>;
}
declare module 'numbro/languages/cs-CZ.js' {
  declare module.exports: $Exports<'numbro/languages/cs-CZ'>;
}
declare module 'numbro/languages/da-DK.js' {
  declare module.exports: $Exports<'numbro/languages/da-DK'>;
}
declare module 'numbro/languages/de-CH.js' {
  declare module.exports: $Exports<'numbro/languages/de-CH'>;
}
declare module 'numbro/languages/de-DE.js' {
  declare module.exports: $Exports<'numbro/languages/de-DE'>;
}
declare module 'numbro/languages/en-GB.js' {
  declare module.exports: $Exports<'numbro/languages/en-GB'>;
}
declare module 'numbro/languages/en-ZA.js' {
  declare module.exports: $Exports<'numbro/languages/en-ZA'>;
}
declare module 'numbro/languages/es-AR.js' {
  declare module.exports: $Exports<'numbro/languages/es-AR'>;
}
declare module 'numbro/languages/es-ES.js' {
  declare module.exports: $Exports<'numbro/languages/es-ES'>;
}
declare module 'numbro/languages/et-EE.js' {
  declare module.exports: $Exports<'numbro/languages/et-EE'>;
}
declare module 'numbro/languages/fa-IR.js' {
  declare module.exports: $Exports<'numbro/languages/fa-IR'>;
}
declare module 'numbro/languages/fi-FI.js' {
  declare module.exports: $Exports<'numbro/languages/fi-FI'>;
}
declare module 'numbro/languages/fil-PH.js' {
  declare module.exports: $Exports<'numbro/languages/fil-PH'>;
}
declare module 'numbro/languages/fr-CA.js' {
  declare module.exports: $Exports<'numbro/languages/fr-CA'>;
}
declare module 'numbro/languages/fr-CH.js' {
  declare module.exports: $Exports<'numbro/languages/fr-CH'>;
}
declare module 'numbro/languages/fr-FR.js' {
  declare module.exports: $Exports<'numbro/languages/fr-FR'>;
}
declare module 'numbro/languages/he-IL.js' {
  declare module.exports: $Exports<'numbro/languages/he-IL'>;
}
declare module 'numbro/languages/hu-HU.js' {
  declare module.exports: $Exports<'numbro/languages/hu-HU'>;
}
declare module 'numbro/languages/it-IT.js' {
  declare module.exports: $Exports<'numbro/languages/it-IT'>;
}
declare module 'numbro/languages/ja-JP.js' {
  declare module.exports: $Exports<'numbro/languages/ja-JP'>;
}
declare module 'numbro/languages/lv-LV.js' {
  declare module.exports: $Exports<'numbro/languages/lv-LV'>;
}
declare module 'numbro/languages/nb-NO.js' {
  declare module.exports: $Exports<'numbro/languages/nb-NO'>;
}
declare module 'numbro/languages/nl-BE.js' {
  declare module.exports: $Exports<'numbro/languages/nl-BE'>;
}
declare module 'numbro/languages/nl-NL.js' {
  declare module.exports: $Exports<'numbro/languages/nl-NL'>;
}
declare module 'numbro/languages/pl-PL.js' {
  declare module.exports: $Exports<'numbro/languages/pl-PL'>;
}
declare module 'numbro/languages/pt-BR.js' {
  declare module.exports: $Exports<'numbro/languages/pt-BR'>;
}
declare module 'numbro/languages/pt-PT.js' {
  declare module.exports: $Exports<'numbro/languages/pt-PT'>;
}
declare module 'numbro/languages/ru-RU.js' {
  declare module.exports: $Exports<'numbro/languages/ru-RU'>;
}
declare module 'numbro/languages/ru-UA.js' {
  declare module.exports: $Exports<'numbro/languages/ru-UA'>;
}
declare module 'numbro/languages/sk-SK.js' {
  declare module.exports: $Exports<'numbro/languages/sk-SK'>;
}
declare module 'numbro/languages/sv-SE.js' {
  declare module.exports: $Exports<'numbro/languages/sv-SE'>;
}
declare module 'numbro/languages/th-TH.js' {
  declare module.exports: $Exports<'numbro/languages/th-TH'>;
}
declare module 'numbro/languages/tr-TR.js' {
  declare module.exports: $Exports<'numbro/languages/tr-TR'>;
}
declare module 'numbro/languages/uk-UA.js' {
  declare module.exports: $Exports<'numbro/languages/uk-UA'>;
}
declare module 'numbro/languages/zh-CN.js' {
  declare module.exports: $Exports<'numbro/languages/zh-CN'>;
}
declare module 'numbro/numbro.js' {
  declare module.exports: $Exports<'numbro/numbro'>;
}
declare module 'numbro/tests/languages/all.js' {
  declare module.exports: $Exports<'numbro/tests/languages/all'>;
}
declare module 'numbro/tests/languages/cs-CZ.js' {
  declare module.exports: $Exports<'numbro/tests/languages/cs-CZ'>;
}
declare module 'numbro/tests/languages/da-DK.js' {
  declare module.exports: $Exports<'numbro/tests/languages/da-DK'>;
}
declare module 'numbro/tests/languages/de-CH.js' {
  declare module.exports: $Exports<'numbro/tests/languages/de-CH'>;
}
declare module 'numbro/tests/languages/de-DE.js' {
  declare module.exports: $Exports<'numbro/tests/languages/de-DE'>;
}
declare module 'numbro/tests/languages/en-GB.js' {
  declare module.exports: $Exports<'numbro/tests/languages/en-GB'>;
}
declare module 'numbro/tests/languages/en-US.js' {
  declare module.exports: $Exports<'numbro/tests/languages/en-US'>;
}
declare module 'numbro/tests/languages/en-ZA.js' {
  declare module.exports: $Exports<'numbro/tests/languages/en-ZA'>;
}
declare module 'numbro/tests/languages/es-AR.js' {
  declare module.exports: $Exports<'numbro/tests/languages/es-AR'>;
}
declare module 'numbro/tests/languages/es-ES.js' {
  declare module.exports: $Exports<'numbro/tests/languages/es-ES'>;
}
declare module 'numbro/tests/languages/et-EE.js' {
  declare module.exports: $Exports<'numbro/tests/languages/et-EE'>;
}
declare module 'numbro/tests/languages/fa-IR.js' {
  declare module.exports: $Exports<'numbro/tests/languages/fa-IR'>;
}
declare module 'numbro/tests/languages/fi-FI.js' {
  declare module.exports: $Exports<'numbro/tests/languages/fi-FI'>;
}
declare module 'numbro/tests/languages/fil-PH.js' {
  declare module.exports: $Exports<'numbro/tests/languages/fil-PH'>;
}
declare module 'numbro/tests/languages/fr-CA.js' {
  declare module.exports: $Exports<'numbro/tests/languages/fr-CA'>;
}
declare module 'numbro/tests/languages/fr-CH.js' {
  declare module.exports: $Exports<'numbro/tests/languages/fr-CH'>;
}
declare module 'numbro/tests/languages/fr-FR.js' {
  declare module.exports: $Exports<'numbro/tests/languages/fr-FR'>;
}
declare module 'numbro/tests/languages/he-IL.js' {
  declare module.exports: $Exports<'numbro/tests/languages/he-IL'>;
}
declare module 'numbro/tests/languages/hu-HU.js' {
  declare module.exports: $Exports<'numbro/tests/languages/hu-HU'>;
}
declare module 'numbro/tests/languages/it-IT.js' {
  declare module.exports: $Exports<'numbro/tests/languages/it-IT'>;
}
declare module 'numbro/tests/languages/ja-JP.js' {
  declare module.exports: $Exports<'numbro/tests/languages/ja-JP'>;
}
declare module 'numbro/tests/languages/locale-codes.js' {
  declare module.exports: $Exports<'numbro/tests/languages/locale-codes'>;
}
declare module 'numbro/tests/languages/lv-LV.js' {
  declare module.exports: $Exports<'numbro/tests/languages/lv-LV'>;
}
declare module 'numbro/tests/languages/nl-BE.js' {
  declare module.exports: $Exports<'numbro/tests/languages/nl-BE'>;
}
declare module 'numbro/tests/languages/nl-NL.js' {
  declare module.exports: $Exports<'numbro/tests/languages/nl-NL'>;
}
declare module 'numbro/tests/languages/pl-PL.js' {
  declare module.exports: $Exports<'numbro/tests/languages/pl-PL'>;
}
declare module 'numbro/tests/languages/pt-BR.js' {
  declare module.exports: $Exports<'numbro/tests/languages/pt-BR'>;
}
declare module 'numbro/tests/languages/pt-PT.js' {
  declare module.exports: $Exports<'numbro/tests/languages/pt-PT'>;
}
declare module 'numbro/tests/languages/ru-RU.js' {
  declare module.exports: $Exports<'numbro/tests/languages/ru-RU'>;
}
declare module 'numbro/tests/languages/ru-UA.js' {
  declare module.exports: $Exports<'numbro/tests/languages/ru-UA'>;
}
declare module 'numbro/tests/languages/sk-SK.js' {
  declare module.exports: $Exports<'numbro/tests/languages/sk-SK'>;
}
declare module 'numbro/tests/languages/sv-SE.js' {
  declare module.exports: $Exports<'numbro/tests/languages/sv-SE'>;
}
declare module 'numbro/tests/languages/th-TH.js' {
  declare module.exports: $Exports<'numbro/tests/languages/th-TH'>;
}
declare module 'numbro/tests/languages/tr-TR.js' {
  declare module.exports: $Exports<'numbro/tests/languages/tr-TR'>;
}
declare module 'numbro/tests/languages/uk-UA.js' {
  declare module.exports: $Exports<'numbro/tests/languages/uk-UA'>;
}
declare module 'numbro/tests/languages/zh-CN.js' {
  declare module.exports: $Exports<'numbro/tests/languages/zh-CN'>;
}
declare module 'numbro/tests/numbro/format.js' {
  declare module.exports: $Exports<'numbro/tests/numbro/format'>;
}
declare module 'numbro/tests/numbro/manipulate.js' {
  declare module.exports: $Exports<'numbro/tests/numbro/manipulate'>;
}
declare module 'numbro/tests/numbro/misc.js' {
  declare module.exports: $Exports<'numbro/tests/numbro/misc'>;
}
declare module 'numbro/tests/numbro/unformat.js' {
  declare module.exports: $Exports<'numbro/tests/numbro/unformat'>;
}
declare module 'numbro/tests/numbro/validate.js' {
  declare module.exports: $Exports<'numbro/tests/numbro/validate'>;
}
