// flow-typed signature: fb69a13dda73d576c8cd519270a27502
// flow-typed version: <<STUB>>/react-swipe_v5.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipe/dist/react-swipe' {
  declare module.exports: any;
}

declare module 'react-swipe/dist/react-swipe.min' {
  declare module.exports: any;
}

declare module 'react-swipe/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipe/dist/react-swipe.js' {
  declare module.exports: $Exports<'react-swipe/dist/react-swipe'>;
}
declare module 'react-swipe/dist/react-swipe.min.js' {
  declare module.exports: $Exports<'react-swipe/dist/react-swipe.min'>;
}
declare module 'react-swipe/index' {
  declare module.exports: $Exports<'react-swipe'>;
}
declare module 'react-swipe/index.js' {
  declare module.exports: $Exports<'react-swipe'>;
}
declare module 'react-swipe/webpack.config.js' {
  declare module.exports: $Exports<'react-swipe/webpack.config'>;
}
