// flow-typed signature: 6b69a0fb0fab7428216d71272588ba25
// flow-typed version: <<STUB>>/stylelint-config-rational-order_v^0.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-rational-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-rational-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-rational-order/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-rational-order/index' {
  declare module.exports: $Exports<'stylelint-config-rational-order'>;
}
declare module 'stylelint-config-rational-order/index.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order'>;
}
declare module 'stylelint-config-rational-order/index.test.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/index.test'>;
}
