// flow-typed signature: 99595278f0c360432447e1fbe3591fed
// flow-typed version: <<STUB>>/react-datepicker_v^1.4.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datepicker/dist/react-datepicker' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist/react-datepicker.min' {
  declare module.exports: any;
}

declare module 'react-datepicker/es/index' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datepicker/dist/react-datepicker.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker'>;
}
declare module 'react-datepicker/dist/react-datepicker.min.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker.min'>;
}
declare module 'react-datepicker/es/index.js' {
  declare module.exports: $Exports<'react-datepicker/es/index'>;
}
declare module 'react-datepicker/lib/index.js' {
  declare module.exports: $Exports<'react-datepicker/lib/index'>;
}
