// flow-typed signature: 0bc3288072146440770073e45d10e91d
// flow-typed version: <<STUB>>/@shared-components/api-config_v^1.4.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shared-components/api-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shared-components/api-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shared-components/api-config/build/bundle.development' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/build/bundle.preproduction' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/build/bundle.production' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/build/index' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/flow-coverage-report_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/prettier-check_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/react-test-renderer_v16.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/webpack-bundle-analyzer_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/jest.config' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/src/environments' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/src/index' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/src/index.test' {
  declare module.exports: any;
}

declare module '@shared-components/api-config/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shared-components/api-config/build/bundle.development.js' {
  declare module.exports: $Exports<'@shared-components/api-config/build/bundle.development'>;
}
declare module '@shared-components/api-config/build/bundle.preproduction.js' {
  declare module.exports: $Exports<'@shared-components/api-config/build/bundle.preproduction'>;
}
declare module '@shared-components/api-config/build/bundle.production.js' {
  declare module.exports: $Exports<'@shared-components/api-config/build/bundle.production'>;
}
declare module '@shared-components/api-config/build/index.js' {
  declare module.exports: $Exports<'@shared-components/api-config/build/index'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-loader_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/flow-coverage-report_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/flow-coverage-report_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/jest_v22.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/prettier-check_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/prettier-check_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/react-test-renderer_v16.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/react-test-renderer_v16.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/webpack-bundle-analyzer_vx.x.x'>;
}
declare module '@shared-components/api-config/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@shared-components/api-config/flow-typed/npm/webpack-cli_vx.x.x'>;
}
declare module '@shared-components/api-config/jest.config.js' {
  declare module.exports: $Exports<'@shared-components/api-config/jest.config'>;
}
declare module '@shared-components/api-config/src/environments.js' {
  declare module.exports: $Exports<'@shared-components/api-config/src/environments'>;
}
declare module '@shared-components/api-config/src/index.js' {
  declare module.exports: $Exports<'@shared-components/api-config/src/index'>;
}
declare module '@shared-components/api-config/src/index.test.js' {
  declare module.exports: $Exports<'@shared-components/api-config/src/index.test'>;
}
declare module '@shared-components/api-config/webpack.config.js' {
  declare module.exports: $Exports<'@shared-components/api-config/webpack.config'>;
}
