// flow-typed signature: b418861496110c665e8162d50508f113
// flow-typed version: <<STUB>>/@shared-components/language-provider_v^1.3.19/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shared-components/language-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shared-components/language-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shared-components/language-provider/build/bundle.development' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/build/bundle.preproduction' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/build/bundle.production' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/build/index' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/@shared-components/api-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/@shared-components/atoms_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/flow-coverage-report_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/prettier-check_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/react-intl_v2.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/react-test-renderer_v16.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/superagent_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/webpack-bundle-analyzer_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/jest.config' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/src/api' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/src/component' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/src/container' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/src/index' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/src/stories' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/src/test' {
  declare module.exports: any;
}

declare module '@shared-components/language-provider/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shared-components/language-provider/build/bundle.development.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/build/bundle.development'
  >;
}
declare module '@shared-components/language-provider/build/bundle.preproduction.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/build/bundle.preproduction'
  >;
}
declare module '@shared-components/language-provider/build/bundle.production.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/build/bundle.production'
  >;
}
declare module '@shared-components/language-provider/build/index.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/build/index'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/@shared-components/api-config_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/@shared-components/api-config_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/@shared-components/atoms_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/@shared-components/atoms_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-cli_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-core_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-eslint_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-jest_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-loader_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-polyfill_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-preset-env_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-preset-react_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/babel-preset-stage-0_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/cross-env_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-config-airbnb_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-config-prettier_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-loader_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-plugin-import_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/eslint-plugin-react_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/flow-bin_v0.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/flow-coverage-report_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/flow-coverage-report_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/jest_v22.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/lodash_v4.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/prettier_v1.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/prettier-check_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/prettier-check_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/react-intl_v2.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/react-intl_v2.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/react-test-renderer_v16.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/react-test-renderer_v16.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/superagent_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/superagent_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/webpack_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/webpack-bundle-analyzer_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/flow-typed/npm/webpack-cli_vx.x.x'
  >;
}
declare module '@shared-components/language-provider/jest.config.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/jest.config'
  >;
}
declare module '@shared-components/language-provider/src/api.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/src/api'
  >;
}
declare module '@shared-components/language-provider/src/component.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/src/component'
  >;
}
declare module '@shared-components/language-provider/src/container.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/src/container'
  >;
}
declare module '@shared-components/language-provider/src/index.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/src/index'
  >;
}
declare module '@shared-components/language-provider/src/stories.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/src/stories'
  >;
}
declare module '@shared-components/language-provider/src/test.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/src/test'
  >;
}
declare module '@shared-components/language-provider/webpack.config.js' {
  declare module.exports: $Exports<
    '@shared-components/language-provider/webpack.config'
  >;
}
