// flow-typed signature: aafdaf95ce3a7120097523e153ef63db
// flow-typed version: <<STUB>>/@shared-components/atoms_v1.4.38/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shared-components/atoms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shared-components/atoms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shared-components/atoms/build/bundle.development' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/build/bundle.preproduction' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/build/bundle.production' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/build/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/flow-coverage-report_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/immutable_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/jest-styled-components_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/mini-css-extract-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/prettier-check_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/react-intl_v2.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/react-onclickoutside_v6.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/react-test-renderer_v16.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/react-tooltip_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/redux-saga_v0.16.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/reselect_v3.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/styled-components_v3.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/url-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/webpack-bundle-analyzer_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/flow-typed/TableType' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/jest.config' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.theme' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Checkbox/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Checkbox/tests/Checkbox.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Dropdown/Dropdown.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Dropdown/Dropdown.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Dropdown/Dropdown.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Dropdown/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Dropdown/test/Dropdown.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Icon/Icon.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Icon/Icon.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Icon/Icon.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Icon/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Icon/test/Icon.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoaderWrapper/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.container' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoaderWrapper/tests/LoaderWrapper.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoadingIndicator/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/LoadingIndicator/tests/LoadingIndicator.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/ProgressBar/component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/ProgressBar/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/ProgressBar/style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/TabTitle/component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/TabTitle/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/TabTitle/style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/NavBar/theme' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Radio/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Radio/Radio.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Radio/Radio.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Radio/Radio.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Radio/Radio.theme' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Radio/tests/Radio.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/StarRating/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/StarRating/StarRating.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/StarRating/StarRating.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/StarRating/StarRating.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/StarRating/tests/StarRating.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Table/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Table/Table.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Table/Table.stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Table/Table.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Table/tests/Table.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableBySection/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableBySection/TableBySection.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableBySection/TableBySection.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableBySection/tests/TableBySection.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/Cell/Cell.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/Cell/Cell.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/Cell/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/ProductLink/ProductLink.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/ProductLink/ProductLink.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/ProductLink/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/ProductLink/tests/ProductLink.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/Row/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/Row/Row.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/Row/Row.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/SortIcon/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.container' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/SortIcon/tests/SortIcon.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/TableCellPerformance.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/TableCellPerformance.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/tests/TableCellPerformance.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellText/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellText/TableCellText.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellText/TableCellText.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableCellText/tests/TableCellText.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeader/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeader/TableHeader.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeader/TableHeader.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeader/tests/TableHeader.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/TableHeaderTitle.component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/TableHeaderTitle.style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/tests/TableHeaderTitle.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Tooltip/component' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Tooltip/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Tooltip/stories' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Tooltip/style' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/components/Tooltip/test/Tooltip.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/index.watcher' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/actions' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/constants' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/decorators' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/reducer' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/selectors' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/tests/decorator.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/tests/reducer.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/loader/tests/selectors.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/table/actions' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/table/reducer' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/table/selectors' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/redux/table/tests/reducer.test' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/style/index' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/utils/prettyPrintProps' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/src/utils/to-js' {
  declare module.exports: any;
}

declare module '@shared-components/atoms/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shared-components/atoms/build/bundle.development.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/build/bundle.development'
  >;
}
declare module '@shared-components/atoms/build/bundle.preproduction.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/build/bundle.preproduction'
  >;
}
declare module '@shared-components/atoms/build/bundle.production.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/build/bundle.production'
  >;
}
declare module '@shared-components/atoms/build/index.js' {
  declare module.exports: $Exports<'@shared-components/atoms/build/index'>;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-cli_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-core_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-eslint_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-jest_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-loader_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-polyfill_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-preset-env_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-preset-react_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/babel-preset-stage-0_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/cross-env_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-config-airbnb_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-config-prettier_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-loader_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-plugin-import_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/eslint-plugin-react_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/flow-bin_v0.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/flow-coverage-report_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/flow-coverage-report_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/immutable_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/immutable_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/jest_v22.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/jest-styled-components_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/jest-styled-components_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/lodash_v4.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/mini-css-extract-plugin_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/mini-css-extract-plugin_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/prettier_v1.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/prettier-check_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/prettier-check_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/react-intl_v2.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/react-intl_v2.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/react-onclickoutside_v6.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/react-onclickoutside_v6.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/react-redux_v5.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/react-test-renderer_v16.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/react-test-renderer_v16.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/react-tooltip_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/react-tooltip_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/redux_v3.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/redux-saga_v0.16.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/redux-saga_v0.16.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/reselect_v3.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/reselect_v3.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/styled-components_v3.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/styled-components_v3.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/url-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/url-loader_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/webpack_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/webpack-bundle-analyzer_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/webpack-cli_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/npm/webpack-dev-server_vx.x.x'
  >;
}
declare module '@shared-components/atoms/flow-typed/TableType.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/flow-typed/TableType'
  >;
}
declare module '@shared-components/atoms/jest.config.js' {
  declare module.exports: $Exports<'@shared-components/atoms/jest.config'>;
}
declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Checkbox/Checkbox.component'
  >;
}
declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Checkbox/Checkbox.stories'
  >;
}
declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Checkbox/Checkbox.style'
  >;
}
declare module '@shared-components/atoms/src/components/Checkbox/Checkbox.theme.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Checkbox/Checkbox.theme'
  >;
}
declare module '@shared-components/atoms/src/components/Checkbox/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Checkbox/index'
  >;
}
declare module '@shared-components/atoms/src/components/Checkbox/tests/Checkbox.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Checkbox/tests/Checkbox.test'
  >;
}
declare module '@shared-components/atoms/src/components/Dropdown/Dropdown.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Dropdown/Dropdown.component'
  >;
}
declare module '@shared-components/atoms/src/components/Dropdown/Dropdown.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Dropdown/Dropdown.stories'
  >;
}
declare module '@shared-components/atoms/src/components/Dropdown/Dropdown.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Dropdown/Dropdown.style'
  >;
}
declare module '@shared-components/atoms/src/components/Dropdown/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Dropdown/index'
  >;
}
declare module '@shared-components/atoms/src/components/Dropdown/test/Dropdown.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Dropdown/test/Dropdown.test'
  >;
}
declare module '@shared-components/atoms/src/components/Icon/Icon.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Icon/Icon.component'
  >;
}
declare module '@shared-components/atoms/src/components/Icon/Icon.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Icon/Icon.stories'
  >;
}
declare module '@shared-components/atoms/src/components/Icon/Icon.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Icon/Icon.style'
  >;
}
declare module '@shared-components/atoms/src/components/Icon/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Icon/index'
  >;
}
declare module '@shared-components/atoms/src/components/Icon/test/Icon.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Icon/test/Icon.test'
  >;
}
declare module '@shared-components/atoms/src/components/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/index'
  >;
}
declare module '@shared-components/atoms/src/components/LoaderWrapper/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoaderWrapper/index'
  >;
}
declare module '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.component'
  >;
}
declare module '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.container.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.container'
  >;
}
declare module '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoaderWrapper/LoaderWrapper.style'
  >;
}
declare module '@shared-components/atoms/src/components/LoaderWrapper/tests/LoaderWrapper.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoaderWrapper/tests/LoaderWrapper.test'
  >;
}
declare module '@shared-components/atoms/src/components/LoadingIndicator/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoadingIndicator/index'
  >;
}
declare module '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.component'
  >;
}
declare module '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.stories'
  >;
}
declare module '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoadingIndicator/LoadingIndicator.style'
  >;
}
declare module '@shared-components/atoms/src/components/LoadingIndicator/tests/LoadingIndicator.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/LoadingIndicator/tests/LoadingIndicator.test'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/component'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/index'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/ProgressBar/component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/ProgressBar/component'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/ProgressBar/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/ProgressBar/index'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/ProgressBar/style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/ProgressBar/style'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/stories'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/style'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/TabTitle/component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/TabTitle/component'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/TabTitle/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/TabTitle/index'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/TabTitle/style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/TabTitle/style'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/test'
  >;
}
declare module '@shared-components/atoms/src/components/NavBar/theme.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/NavBar/theme'
  >;
}
declare module '@shared-components/atoms/src/components/Radio/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Radio/index'
  >;
}
declare module '@shared-components/atoms/src/components/Radio/Radio.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Radio/Radio.component'
  >;
}
declare module '@shared-components/atoms/src/components/Radio/Radio.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Radio/Radio.stories'
  >;
}
declare module '@shared-components/atoms/src/components/Radio/Radio.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Radio/Radio.style'
  >;
}
declare module '@shared-components/atoms/src/components/Radio/Radio.theme.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Radio/Radio.theme'
  >;
}
declare module '@shared-components/atoms/src/components/Radio/tests/Radio.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Radio/tests/Radio.test'
  >;
}
declare module '@shared-components/atoms/src/components/StarRating/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/StarRating/index'
  >;
}
declare module '@shared-components/atoms/src/components/StarRating/StarRating.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/StarRating/StarRating.component'
  >;
}
declare module '@shared-components/atoms/src/components/StarRating/StarRating.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/StarRating/StarRating.stories'
  >;
}
declare module '@shared-components/atoms/src/components/StarRating/StarRating.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/StarRating/StarRating.style'
  >;
}
declare module '@shared-components/atoms/src/components/StarRating/tests/StarRating.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/StarRating/tests/StarRating.test'
  >;
}
declare module '@shared-components/atoms/src/components/Table/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Table/index'
  >;
}
declare module '@shared-components/atoms/src/components/Table/Table.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Table/Table.component'
  >;
}
declare module '@shared-components/atoms/src/components/Table/Table.stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Table/Table.stories'
  >;
}
declare module '@shared-components/atoms/src/components/Table/Table.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Table/Table.style'
  >;
}
declare module '@shared-components/atoms/src/components/Table/tests/Table.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Table/tests/Table.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableBySection/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableBySection/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableBySection/TableBySection.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableBySection/TableBySection.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableBySection/TableBySection.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableBySection/TableBySection.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableBySection/tests/TableBySection.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableBySection/tests/TableBySection.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/Cell/Cell.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/Cell/Cell.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/Cell/Cell.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/Cell/Cell.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/Cell/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/Cell/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/ProductLink/ProductLink.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/ProductLink/ProductLink.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/ProductLink/ProductLink.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/ProductLink/ProductLink.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/ProductLink/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/ProductLink/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/ProductLink/tests/ProductLink.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/ProductLink/tests/ProductLink.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/Row/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/Row/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/Row/Row.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/Row/Row.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/Row/Row.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/Row/Row.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/SortIcon/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/SortIcon/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.container.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.container'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/SortIcon/SortIcon.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/SortIcon/tests/SortIcon.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/SortIcon/tests/SortIcon.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellPerformance/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/TableCellPerformance.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellPerformance/TableCellPerformance.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/TableCellPerformance.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellPerformance/TableCellPerformance.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellPerformance/tests/TableCellPerformance.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellPerformance/tests/TableCellPerformance.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellText/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellText/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellText/TableCellText.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellText/TableCellText.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellText/TableCellText.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellText/TableCellText.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableCellText/tests/TableCellText.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableCellText/tests/TableCellText.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeader/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeader/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeader/TableHeader.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeader/TableHeader.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeader/TableHeader.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeader/TableHeader.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeader/tests/TableHeader.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeader/tests/TableHeader.test'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/index'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/TableHeaderTitle.component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/TableHeaderTitle.component'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/TableHeaderTitle.style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/TableHeaderTitle.style'
  >;
}
declare module '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/tests/TableHeaderTitle.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/TableElement/TableHeaderTitle/tests/TableHeaderTitle.test'
  >;
}
declare module '@shared-components/atoms/src/components/Tooltip/component.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Tooltip/component'
  >;
}
declare module '@shared-components/atoms/src/components/Tooltip/index.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Tooltip/index'
  >;
}
declare module '@shared-components/atoms/src/components/Tooltip/stories.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Tooltip/stories'
  >;
}
declare module '@shared-components/atoms/src/components/Tooltip/style.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Tooltip/style'
  >;
}
declare module '@shared-components/atoms/src/components/Tooltip/test/Tooltip.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/components/Tooltip/test/Tooltip.test'
  >;
}
declare module '@shared-components/atoms/src/index.js' {
  declare module.exports: $Exports<'@shared-components/atoms/src/index'>;
}
declare module '@shared-components/atoms/src/index.watcher.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/index.watcher'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/actions.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/actions'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/constants.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/constants'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/decorators.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/decorators'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/reducer.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/reducer'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/selectors.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/selectors'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/tests/decorator.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/tests/decorator.test'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/tests/reducer.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/tests/reducer.test'
  >;
}
declare module '@shared-components/atoms/src/redux/loader/tests/selectors.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/loader/tests/selectors.test'
  >;
}
declare module '@shared-components/atoms/src/redux/table/actions.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/table/actions'
  >;
}
declare module '@shared-components/atoms/src/redux/table/reducer.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/table/reducer'
  >;
}
declare module '@shared-components/atoms/src/redux/table/selectors.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/table/selectors'
  >;
}
declare module '@shared-components/atoms/src/redux/table/tests/reducer.test.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/redux/table/tests/reducer.test'
  >;
}
declare module '@shared-components/atoms/src/style/index.js' {
  declare module.exports: $Exports<'@shared-components/atoms/src/style/index'>;
}
declare module '@shared-components/atoms/src/utils/prettyPrintProps.js' {
  declare module.exports: $Exports<
    '@shared-components/atoms/src/utils/prettyPrintProps'
  >;
}
declare module '@shared-components/atoms/src/utils/to-js.js' {
  declare module.exports: $Exports<'@shared-components/atoms/src/utils/to-js'>;
}
declare module '@shared-components/atoms/webpack.config.js' {
  declare module.exports: $Exports<'@shared-components/atoms/webpack.config'>;
}
